# Generated by Django 4.2.11 on 2024-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        ),
    ]
