# Generated by Django 4.2.11 on 2024-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_km",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="title_km",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
