# Generated by Django 4.2.11 on 2024-03-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
