# Generated by Django 4.2.11 on 2024-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_testimonial_message_en_testimonial_message_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
    ]
