# Generated by Django 4.2.11 on 2024-03-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="answer_en",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_fr",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_km",
            field=models.TextField(null=True, verbose_name="Answer"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_fr",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_km",
            field=models.CharField(max_length=255, null=True, verbose_name="Question"),
        ),
    ]
