# Generated by Django 4.2.11 on 2024-03-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_faq_answer_en_faq_answer_fr_faq_answer_km_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concierge_description",
                    models.TextField(
                        help_text="Description of the concierge company services.",
                        verbose_name="Concierge Company Description",
                    ),
                ),
            ],
        ),
    ]
