# Generated by Django 4.2.11 on 2024-03-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_siteinformation_concierge_description_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offering",
                        to="blog.service",
                    ),
                ),
            ],
        ),
    ]
