# Generated by Django 4.2.11 on 2024-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_offering"),
    ]

    operations = [
        migrations.AddField(
            model_name="offering",
            name="text_en",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="text_fr",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="text_km",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
