# Generated by Django 4.2.11 on 2024-03-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_offering_text_en_offering_text_fr_offering_text_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offering",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerings",
                to="blog.service",
            ),
        ),
    ]
