# Generated by Django 4.2.11 on 2024-03-24 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_offering_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="is_general",
            field=models.BooleanField(
                default=False,
                help_text="Mark this FAQ as a general FAQ that applies to all services.",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faqs",
                to="blog.service",
            ),
        ),
    ]
