# Generated by Django 4.2.11 on 2024-03-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_faq_is_general_faq_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "subtitle",
                    models.TextField(blank=True, null=True, verbose_name="Subtitle"),
                ),
                ("image", models.ImageField(upload_to="images/", verbose_name="Image")),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Button Text"
                    ),
                ),
                (
                    "button_link",
                    models.URLField(blank=True, null=True, verbose_name="Button Link"),
                ),
            ],
            options={
                "verbose_name": "Home Page Section",
                "verbose_name_plural": "Home Page Sections",
            },
        ),
    ]
