# Generated by Django 4.2.11 on 2024-03-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_homepagesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesection",
            name="button_link_en",
            field=models.URLField(blank=True, null=True, verbose_name="Button Link"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_link_fr",
            field=models.URLField(blank=True, null=True, verbose_name="Button Link"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_link_km",
            field=models.URLField(blank=True, null=True, verbose_name="Button Link"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_text_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_text_fr",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_text_km",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle_en",
            field=models.TextField(blank=True, null=True, verbose_name="Subtitle"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Subtitle"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle_km",
            field=models.TextField(blank=True, null=True, verbose_name="Subtitle"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="title_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="title_km",
            field=models.CharField(max_length=200, null=True, verbose_name="Title"),
        ),
    ]
