# Generated by Django 4.2.11 on 2024-03-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_homepagesection_button_link_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_link",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_link_en",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_link_fr",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_link_km",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_text",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_text_en",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_text_fr",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="button_text_km",
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="first_button_text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="first_button_text_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="first_button_text_fr",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="first_button_text_km",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="First Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="second_button_text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Second Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="second_button_text_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Second Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="second_button_text_fr",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Second Button Text"
            ),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="second_button_text_km",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Second Button Text"
            ),
        ),
    ]
