# Generated by Django 4.2.11 on 2024-04-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_remove_homepagesection_button_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offering",
            old_name="text",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="offering",
            old_name="text_en",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="offering",
            old_name="text_fr",
            new_name="title_fr",
        ),
        migrations.RenameField(
            model_name="offering",
            old_name="text_km",
            new_name="title_km",
        ),
        migrations.RemoveField(
            model_name="service",
            name="image",
        ),
        migrations.RemoveField(
            model_name="service",
            name="link",
        ),
        migrations.AddField(
            model_name="offering",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offering",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="description_km",
            field=models.TextField(null=True),
        ),
    ]
