# Generated by Django 4.2.11 on 2024-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_rename_text_offering_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="answer_km",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_km",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="first_button_text_km",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="second_button_text_km",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="subtitle_km",
        ),
        migrations.RemoveField(
            model_name="homepagesection",
            name="title_km",
        ),
        migrations.RemoveField(
            model_name="offering",
            name="description_km",
        ),
        migrations.RemoveField(
            model_name="offering",
            name="title_km",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description_km",
        ),
        migrations.RemoveField(
            model_name="service",
            name="title_km",
        ),
        migrations.RemoveField(
            model_name="siteinformation",
            name="concierge_description_km",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="message_km",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="role_km",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
    ]
