# Generated by Django 4.2.11 on 2024-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_remove_faq_answer_af_remove_faq_answer_ar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
            ],
        ),
    ]
