# Generated by Django 4.2.11 on 2024-05-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_examplemodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExampleModel",
        ),
    ]
